name: BountyPlugin
main: com.gmail.panmpan.BountyPlugin.BountyPlugin
version: 1.0
author: Michael Pan
commands:
  startbounty:
    description: 開始新的懸賞
    usage: /<command>
#   tphere:
#     description: 把對方傳送到你的位置 [如果你沒有權限，對方需要打 /tc]
#     usage: /<command> [player]
#   tc:
#     description: 接受傳送
#     usage: /<command>
#   td:
#     description: 拒絕傳送
#     usage: /<command>
# permissions:
#   mimebro.tp:
#     description: Allow you tp to a player without permission
#     default: op